name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: sudo apt-get update -y && sudo apt-get install -y build-essential git python3 libsdl2-dev
    - name: make
      run: make
    - uses: actions/upload-artifact@v1
      with:
        name: libsm64
        path: dist/libsm64.so
  build-macos:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: brew install make mingw-w64 gcc sdl2 pkg-config glew glfw libusb audiofile coreutils
    - name: make
      run: gmake -j
    - uses: actions/upload-artifact@v1
      with:
        name: libsm64
        path: dist/libsm64.dylib
